const statusCode = require('http-status-codes');

module.exports = {
  FAILED_TO_FIND_DATA: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_ADD_DATA: statusCode.CONFLICT,
  FAILED_TO_UPDATE_DATA: statusCode.CONFLICT,
  FAILED_TO_COMPARE_PASSWORDS: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_HASH_PASSWORDS: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_GENERATE_TOKEN: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_CHECK_IF_USER_EXISTS: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_GET_NUMBER_OF_UNBOOKED_SEATS: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_LOG_IN: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_SIGN_UP: statusCode.INTERNAL_SERVER_ERROR,
  FAILED_TO_GET_DATA: statusCode.INTERNAL_SERVER_ERROR,
  USER_NOT_FOUND: statusCode.UNAUTHORIZED,
  USER_ALREADY_EXISTS: statusCode.BAD_REQUEST,
  NO_DATA_WAS_FOUND: statusCode.NOT_FOUND
};
